kind = "web"
previewPath = "/"
title = "Sniper Bot"
version = "1.0.0"
id = "artifacts/sniper-bot"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19939

[services.development]
run = "pnpm --filter @workspace/sniper-bot run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sniper-bot", "run", "build" ]
publicDir = "artifacts/sniper-bot/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19939"
BASE_PATH = "/"
